services:
  nginx:
    container_name: nginx-reserva
    build: ./Nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/autoreserva/keys:/etc/ssl:ro
    env_file:
      - /etc/autoreserva/env/nginx.env

  database:
    container_name: postgres-reserva
    build: ./Postgress
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /etc/autoreserva/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=reserva
    env_file:
      - /etc/autoreserva/env/database.env

  api:
    container_name: api-reserva
    depends_on:
      - database
      - nginx
    build: ./Server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    env_file:
      - /etc/autoreserva/env/api.env
